### ISSUE TITLE
Would it be possible to add microseconds?(HH:MM:SS.mmmuuu)

### ISSUE THREAD

**Issue by diregraph** [fooloomanzoo/datetime-picker#17]
I am trying to add microseconds as well. Kind of stuck. Any help is much appreciated.

**Comment by fooloomanzoo** [comment]
JavaScript's `DateTime` just is using milliseconds, because it is in `iso8086`-Format, like this element. So the `datetime`-String would not be correct, if you add microseconds, so I would guess, it might be the best to extend the element and add a new `property`. The `clamp`-attribute also needs to be handled differently then, so the `datetime-mixin` must be changed for that. Determing `now()` would also be a bit differerent. But I look into it!

**Comment by diregraph** [comment]
Thank you very much.

**Comment by fooloomanzoo** [comment]
This should work:

````html
    <link rel="import" href="../polymer/polymer-element.html">
    <link rel="import" href="../input-picker-pattern/overlay-picker-mixin.html">
    <link rel="import" href="../datetime-picker/time-picker.html">

    <dom-module id="ms-time-picker">
      <script>
        /**
         *  @customElement
         *  @polymer
         *
         *  @appliesMixin OverlayPickerMixin
         *  @extends TimePicker
         *
         **/
        class MsTimePicker extends OverlayPickerMixin(TimePicker) {

          static get is() {
            return 'ms-time-picker';
          }

          static get properties() {
            return {

              microseconds: {
                type: Number,
                value: 0,
                notify: true
              },

              clamp: {
                type: String,
                value: ''
              },

              hour12: {
                type: Boolean,
                value: false,
                readOnly: true
              }

            }
          }

          static get replacementInputTemplate() {
            return `
              ${super.replacementInputTemplate}
              <number-input hidden$="[[_hideMilliseconds]]" value="{{microseconds}}" min="0" max="999" disabled="[[disabled]]" placeholder="000"></number-input>
            `;
          }

          static get timeTemplate() {
            return `
              <div id="timer" hidden$="[[_hideHours]]">
                <div class="field">
                  <svg class="icon switch" viewBox="0 0 24 24" prop="Hours" step="1"><g><path d="M12 8l-6 6 1.41 1.41L12 10.83l4.59 4.58L18 14z"/></g></svg>
                  <number-input hidden$="[[hour12]]" index="1" class="time" min="0" max="23" pad-length="2" value="{{hours}}" placeholder="00"></number-input>
                  <number-input hidden$="[[!hour12]]" index="1" class="time" min="1" max="12" pad-length="2" value="{{hours12}}" placeholder="00"></number-input>
                  <svg class="icon switch" viewBox="0 0 24 24" prop="Hours" step="-1"><g><path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"/></g></svg>
                </div>
                <span hidden$="[[_hideMinutes]]">[[_localTimeSeparator]]</span>
                <div class="field" hidden$="[[_hideMinutes]]">
                  <svg class="icon switch" viewBox="0 0 24 24" prop="Minutes" step="1"><g><path d="M12 8l-6 6 1.41 1.41L12 10.83l4.59 4.58L18 14z"/></g></svg>
                  <number-input class="time" index="3" min="0" max="59" index="2" pad-length="2" value="{{minutes}}" placeholder="00"></number-input>
                  <svg class="icon switch" viewBox="0 0 24 24" prop="Minutes" step="-1"><g><path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"/></g></svg>
                </div>
                <span hidden$="[[_hideSeconds]]">[[_localTimeSeparator]]</span>
                <div class="field" hidden$="[[_hideSeconds]]">
                  <svg class="icon switch" viewBox="0 0 24 24" prop="Seconds" step="1"><g><path d="M12 8l-6 6 1.41 1.41L12 10.83l4.59 4.58L18 14z"/></g></svg>
                  <number-input class="time" index="5" pad-length="2" min="0" max="59" value="{{seconds}}" placeholder="00"></number-input>
                  <svg class="icon switch" viewBox="0 0 24 24" prop="Seconds" step="-1"><g><path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"/></g></svg>
                </div>
                <span hidden$="[[_hideMilliSeconds]]">[[_localDecimalSeparator]]</span>
                <div class="field" hidden$="[[_hideMilliSeconds]]">
                  <svg class="icon switch" viewBox="0 0 24 24" prop="Milliseconds" step="1"><g><path d="M12 8l-6 6 1.41 1.41L12 10.83l4.59 4.58L18 14z"/></g></svg>
                  <number-input class="time" index="7" pad-length="3" min="0" max="999" value="{{milliseconds}}" placeholder="000"></number-input>
                  <svg class="icon switch" viewBox="0 0 24 24" prop="Milliseconds" step="-1"><g><path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"/></g></svg>
                </div>
                <div class="field" hidden$="[[_hideMilliSeconds]]">
                  <svg class="icon switch" viewBox="0 0 24 24" prop="Microseconds" step="1"><g><path d="M12 8l-6 6 1.41 1.41L12 10.83l4.59 4.58L18 14z"/></g></svg>
                  <number-input class="time" index="9" pad-length="3" min="0" max="999" value="{{microseconds}}" placeholder="000"></number-input>
                  <svg class="icon switch" viewBox="0 0 24 24" prop="Microseconds" step="-1"><g><path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"/></g></svg>
                </div>
              </div>
            `
          }

          _incremProp(prop, step) {
            if (prop === 'Microseconds') {
              this._stopActiveJob();
              this._activeJob = setInterval(() => {
                this.microseconds += step;
              }, 200);
            } else {
              super._incremProp;
            }
          }

        }
        window.customElements.define(MsTimePicker.is, MsTimePicker);
      </script>
    </dom-module>
```

The `microseconds` would be not considered, when computing the date, but you could connect it to another element like `attr="[[datetime]][[microseconds]]"`. You could also go even deaper on `DatetimeMixin` to overwrite a function.

**Comment by diregraph** [comment]
Thank you very much. This is exactly the kind of thing I was looking to implement.  
attr="[[datetime]][[microseconds]]" can be used to get the picked value. 
Cheers! :+1:

**Comment by fooloomanzoo** [comment]
@diregraph You are welcome. There were some mistakes also, that I corrected now

**Comment by diregraph** [comment]
Mistakes in the code you mentioned above or other?
I've been experimenting with your new code (`mu-picker`) and I found out that increment swtiches (`<svg class="icon switch" viewBox="0 0 24 24" prop="Microseconds" step="-1"><g><path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"/></g></svg>`) are not incrementing. I tried fixing(still trying to) `_incremProp` without any luck.

**Comment by fooloomanzoo** [comment]
I changed it the code above, because I also noticed that the switches were not working. This should basically work.

**Comment by diregraph** [comment]
I used the updated code. Still not working. I will keep trying.

**Comment by diregraph** [comment]
Hey @fooloomanzoo , there is some problem with the code above. The  overridden `_incremProp` method is not behaving as your original code as it seems to me. When I remove the overridden method the `mu-picker` works fine for others except microseconds (This is an obvious fact, sorry for that). I am not making any headway. I would be much obliged if you could give me any insight. 
Thank you!

**Comment by fooloomanzoo** [comment]
@diregraph Sorry, I didn't the time last days. The problem in the code was, that it did try to add a String to the property. Attributes are Strings and so this mistake happened.

The solution is no cast it:
```
this.microseconds += (+step);
```

An other mistake in the code was, the function didn't call the super class function with arguments. So it would be correctly:
```
super._incremProp(prop, step);
```

I updated the code in the comment before. Regards!

**Comment by diregraph** [comment]
Great, it works. Thank you very much @fooloomanzoo.
